### ISSUE TITLE
Always given "copy to clipboard" prompt

### ISSUE THREAD

**Issue by thearrow** [nkbt/react-copy-to-clipboard#20]
Latest version of react-copy-to-clipboard (4.1.0)

OSX Chrome Version 49.0.2623.112 (64-bit)
and
OSX Chrome Version 52.0.2705.0 canary (64-bit)

Used inside a React 15 component, imported with 
`import CopyToClipboard from 'react-copy-to-clipboard'`

Used like so:
```
<CopyToClipboard text={window.location.href}
        onCopy={() => this.setState({ copied: true })}>
            <div className='photo-page-permalink'>
              {window.location.href}
            </div>
</CopyToClipboard>
```

Always gives the "Copy to clipboard: Ctrl+C, Enter" prompt, never copies silently.

Example page (http://nkbt.github.io/react-copy-to-clipboard/example/) in same browsers copies to clipboard silently.

On closing the prompt, an error is always thrown:
```
Uncaught TypeError: reselectPrevious is not a function
```

Any ideas?

Thanks!

**Comment by nkbt** [comment]
Hi, @thearrow

> Always gives the "Copy to clipboard: Ctrl+C, Enter" prompt, never copies silently.

What do you mean by this? I do not quite get "gives the ... prompt" part.

**Comment by thearrow** [comment]
Instead of just copying to the clipboard silently, the component always displays the fallback browser prompt: 

<img width="445" alt="screen shot 2016-04-12 at 4 21 58 pm" src="https://cloud.githubusercontent.com/assets/447736/14477402/d4d37d0e-00ca-11e6-8059-c1b021c33d12.png">

Might be an issue with the underlying copy-to-clipboard package...

**Comment by nkbt** [comment]
That happens as a fallback when browser does not support  execCommand natively. Which is quite strange since I am using Chrome Canary as well and it works totally fine for me.

**Comment by nkbt** [comment]
May it be possible due to some browser's privacy settings or ads blocker?

**Comment by thearrow** [comment]
I tried in both browsers in Incognito Mode (no extensions active) - same result.

Tried disabling ad blockers in normal mode - same result.

**Comment by 823844596** [comment]
hi, do you have solved this problem? i met the same question. thanks

**Comment by nkbt** [comment]
I am still not able to reproduce this issue =(

**Comment by 823844596** [comment]
en ...  do you konw any other plugin to copy text in react ? i need to copy text in react,  can you give me any  suggestion? thank you very much!

**Comment by mzamoras** [comment]
I was having the same issue. This library uses "copy-to-clipboard" which happens to use "toggle-selection" library. At the very top of "toggle selection"(index.js) this line is causing troubles:
```javascript
var module = module || {};
```
And after removing that line everything worked just perfectly. Without removing it, the "copy-to-clipboard" library, is unable to reach properly this module using:

```javascript
var deselectCurrent = require("toggle-selection");  // returns {} instead of a function
```

**Just check your console for an error with "reselectPrevious is not a function"**, because that error somehow ends up displaying that prompt which should only be displayed as fallback for unsupported browsers.

Not sure who should fix this issue or if is related directly to this library or author, but at least it's a temporary fix.

**Comment by nkbt** [comment]
Hm that looks like some issue with build process. Do you mind sharing your build config, @mzamoras?

**Comment by mzamoras** [comment]
Sure, no problem ... but ... what you mean by build config?  hope this helps...  
OSX 10.11.4, 
fixed and tried on Safari 9.1 and Chrome 49.0.2623.112

my package.json:

```xml
 {
"devDependencies": {
    "babel-plugin-transform-runtime": "^6.7.5",
    "babel-preset-react-hmre": "^1.1.1",
    "babelify": "^7.2.0",
    "chai": "^3.5.0",
    "envify": "^3.4.0",
    "enzyme": "^2.3.0",
    "expect": "^1.20.1",
    "expect-jsx": "^2.5.1",
    "gulp": "^3.9.1",
    "mocha": "^2.4.5",
    "react-addons-test-utils": "^15.0.2",
    "redux-devtools": "^3.2.0",
    "redux-immutable-state-invariant": "^1.2.3"
  },
"dependencies": {
    "antd": "^0.12.14",
    "bourbon": "^4.2.7",
    "browserify-hmr": "^0.3.1",
    "classnames": "^2.2.3",
    "immutable": "^3.8.1",
    "laravel-elixir": "^5.0.0",
    "laravel-elixir-browserify": "^0.8.1",
    "lodash.merge": "^4.3.5",
    "material-ui": "^0.14.4",
    "normalizr": "^2.0.1",
    "object.assign": "^4.0.3",
    "pusher": "^1.2.1",
    "pusher-js": "^3.1.0",
    "react": "^15.0.1",
    "react-addons-css-transition-group": "^15.0.2",
    "react-copy-to-clipboard": "^4.1.0",
    "react-dom": "^15.0.1",
    "react-mousetrap": "0.0.8",
    "react-redux": "^4.4.5",
    "react-router": "^2.2.4",
    "react-router-redux": "^4.0.2",
    "redux": "^3.4.0",
    "redux-thunk": "^2.0.1",
    "reselect": "^2.5.1",
    "semantic-ui": "^2.1.8"
  }
}
```

**Comment by nkbt** [comment]
@mzamoras well, I meant like `.babelrc`, `webpack.config` or as I can see you use `browserify` and `gulp` (which probably might be the case). I am not a browserify user, but I guess it can treat `module` somewhat differently from how webpack does it.

**Comment by mzamoras** [comment]
.babelrc: //environment name intentionally changed from development to devol, to be able to make some tests with mocha and use hot module reload for development
```xml
{
  "presets": ["es2015", "react"],
  "plugins": ["transform-runtime"],
  "env": {
    "devol": {
      "presets": ["react-hmre"]
    }
  }
}
```

gulpfile: using laravel elixir

```javascript

var elixir = require( 'laravel-elixir' );
var elixirConfig = elixir.config;
var bConfig = elixirConfig.js.browserify;

if ( elixirConfig.production == true ) {
    process.env.NODE_ENV = 'production';
}

bConfig.plugins.push({
    name: 'browserify-hmr',
    options:{}
});

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir( function (mix) {

    mix.sass( 'app.scss' );
    mix.scripts( [ 'base.js' ], 'public/js/base.js' );
    mix.styles( [ '../../../node_modules/antd/lib/index.css','../semantic/dist/semantic.css' ], 'public/css/antd.css' );
    mix.browserify( 'react/app.js', 'public/js/bundle.js');
    
    if (! elixir.config.production) {
        process.env.NODE_ENV = 'devol';
    }
    
    mix.browserSync( {

        proxy: {
            target: "http://test.com",  // locally resolved domain for development
            ws    : true
        },

        open: false,
        reloadOnRestart: true,
        browser: "google chrome",
        injectChanges: true,

        baseDir   : 'public',

        files: [
            'public/css/**/*.css',
            //'public/**/*.html',
            elixirConfig.appPath + '/**/*.php',
            elixirConfig.viewPath + '/**/*.php'
        ]
    } );
} );

´´´

**Comment by nkbt** [comment]
ouch... I thought I'd be able to replicate it, but probably not =(. 

Hi, @sudodoki! Do you have any idea?

**Comment by mzamoras** [comment]
did you try to update the "toggle-selection" library to the latest? ...  in your system the header of that file is exactly to the one I did comment? If so, do you have the same results printing deselectCurrent variable?

```javascript
var module = module || {};
```

 "copy-to-clipboard" library use it with : 
```javascript
var deselectCurrent = require("toggle-selection");

/* Inside this library I tried to check the value of deselectCurrent */
console.log( deselectCurrent );  //  Returns empty object, {}
/* This is causing the incorrect catch on this library's try-catch */

**Comment by stevenmusumeche** [comment]
I'm also having this issue with 4.1.0

**Comment by sudodoki** [comment]
Well, the original issue might be caused by
1) you are trying to call 'copy-to-clipboard' when there's no interaction by user (clicks/keydowns, etc).
>Copy commands triggered from document.execCommand() will only affect the contents of the real clipboard if the event is dispatched from an event that is trusted and triggered by the user, or if the implementation is configured to allow this
2) there's an error thrown somewhere that leads to IE fallback prompt
I think after taking a look at this I will be adding some more info to logging when `debug` option is set to `true` and let you know when you can test the build. That way you would now whether that is a [`SecurityError`](https://dom.spec.whatwg.org/#securityerror) or something else,

**Comment by sudodoki** [comment]
I updated copy-to-clipboard in master branch, could you try checking with it and seeing what the error would be?

**Comment by stevenmusumeche** [comment]
Hi @sudodoki and thank you for the reply.  We ended up using something custom instead of this package.  Directly calling execCommand works fine so I believe there is some issue in the library at play here.

**Comment by nkbt** [comment]
I reckon this one needs to update dep too :). Will do as soon as I am back from holidays (or find better internet here)

**Comment by nkbt** [comment]
Is https://github.com/nkbt/react-copy-to-clipboard/issues/24 the same the problem as here?

**Comment by megapctr** [comment]
I had the same problem, but installing newer `copy-to-clipboard` (`3.0.2` specifically) fixed the problem.

**Comment by nkbt** [comment]
Published + react-copy-to-clipboard@4.1.1

Let me know if issue is still there and reopen ticket!

Thanks!

**Comment by megapctr** [comment]
Installed `4.2.0` and it works, thanks!

**Comment by nkbt** [comment]
Awesome! Thanks for report

**Comment by mzamoras** [comment]
I did update to the 4.2.1 and the problem still exist, then tried the 4.2.0 , still the same. 

Then I re-installed version 4.2.1 and modified the package ( 'toggle-selection' ), and every thing starts working again. 

You should really check that package, it's not just preventing the direct copy or showing the alert box, is also throwing a warning on the console. I mean, **your library works awesome!** And I think those errors are not related to your work but definitely is something that might be causing some troubles or preventing the usage of this library... 

Also I've been thinking that it could be related to the var-word "module" and how browserify or babel handle it **or maybe is webpack the one who is fixing it for you**, because that single line is trying to define "module", although is not registered as an actual keyword, but when debugging the value assigned to that var was always an empty object {}, so no calls or properties are available. In fact, deleting it and the fact that the library works means that it might be not necessary.

You should try deleting it and see if it still works for you as expected.


Finally, after writing this word, I did put the deleted line back and re-compile everything using webpack ... then ... the error was gone!  then remove the line again and tested it again with webpack and also working ...    

I like browserify better, so I prefer removing the line...

**Comment by nkbt** [comment]
@mzamoras have you tried opening an issue in `toggle-selection` repo? I mean I really don't have any sort of control over it... Most likely its build is not perfect and has to be fixed.

**Comment by nkbt** [comment]
https://npmcdn.com/toggle-selection@1.0.4 -- yeah this one is the only one that has that weird `var module = module || {};`

I've never seen anyone doing this. Pretty strange practice.

**Comment by sudodoki** [comment]
@nkbt @mzamoras do you have suggestion on what should be there would gladly modify that piece?

**Comment by mzamoras** [comment]
@sudodoki sure, just delete that line.

Look [https://nodejs.org/api/modules.html#modules_accessing_the_main_module](url) , here Node explains the module or module exports object and usage.

As far as I've read, there is a "module pattern", see example [https://darrenderidder.github.io/talks/ModulePatterns/#/](url), but that specific line is rare and is not included anywhere in the pattern definition, not just in this page, most of the explanations of the pattern definition  don't include it. 

So you would normally use one of this
```js
//file starts
var toggle = function(){
    //... your code here
}
module.exports = toggle; 
//file ends
````
or this form

```js
//file starts
module.exports = function(){
    //your code here
}
//file ends
```

there is no real need to protect against undefined word "module".

**Comment by mzamoras** [comment]
@nkbt I just did fork the repo and  made a pull a request, so waiting to be accepted by @sudodoki , but the package  needs to be also updated on npmjs.com

**Comment by nkbt** [comment]
👌

**Comment by sudodoki** [comment]
@mzamoras published https://www.npmjs.com/package/toggle-selection @ 1.0.5, so it should be fixed now, can you be so kind to check?

**Comment by nkbt** [comment]
I reckon you need to publish copy to clipboard too. And I need to publish
this one after that

**Comment by sudodoki** [comment]
@nkbt copy-to-clipboard depends on [^1.0.3](https://github.com/sudodoki/copy-to-clipboard/blob/master/package.json#L28) and I published 1.0.5 so it should work

**Comment by nkbt** [comment]
Just in case I republished lib so prebuilt script has correct versions of deps.

**Comment by mzamoras** [comment]
sorry to answer that late, but the problem is fixed now, using **react-copy-to-clipboard@4.2.2** with **toggle-selection@1.0.5** !!  @nkbt @sudodoki thank you both!!

**Comment by nkbt** [comment]
\o/ Awesome

**Comment by valentinvoilean** [comment]
I still get this error while trying to test it using Jest & Enzyme.
I have installed toggle-selection 1.0.5 & react-copy-to-clipboard 4.2.3

This is my code:

```
_handleCopy() {
        this.setState({copied: true});
    }

    render() {
        const buttonClass = `${styles.copy} ${this.state.copied ? styles.copied : ''}`;

        return (
            <div className={styles.codeContainer}>
                <code className={styles.code}>{this.props.text}</code>
                <CopyToClipboard text={this.props.text} onCopy={this._handleCopy}>
                    <button className={buttonClass}>Click to copy</button>
                </CopyToClipboard>
            </div>
        );
    }
```

And this is the code for testing:

```
it('should update the button class on click', () => {
        wrapper.find('button').simulate('click');
        expect(wrapper.state().copied).toBe(true);
    });
```

**Comment by valentinvoilean** [comment]
Most probably this problem is because Jest it's using Node to run all the tests unlike the Karma which can be configured to use Chrome launcher.

As a workaround, I did this:
```
it('should update the button class on click', () => {
        wrapper.instance()._handleCopy();
        expect(wrapper.state().copied).toBe(true);
    });
```

But doing this, I'm not testing anymore the CopyToClipboard component.

**Comment by nkbt** [comment]
Well, you should not test 3rd party components. Mock it out completely,
replace with the component that will run you callback and you will now test
your component instead!

Cheers

**Comment by Desintegrator** [comment]
face this issue on 5.0.1
